### ISSUE TITLE
How to run it and using it to score the GAN model?

### ISSUE THREAD

**Issue by jononny** [hvy/chainer-inception-score#2]
just Run like what in the example and I got serval Errors:
python download.py --outfile inception_score.model
>> Downloading inception-2015-12-05.tgz 100.0%('\nSuccesfully downloaded', 'inception-2015-12-05.tgz', 88931400, 'bytes.')
Traceback (most recent call last):
  File "download.py", line 343, in <module>
    main(args)
  File "download.py", line 330, in main
    model = Inception()
  File "/home/chainer-inception-score-master/inception_score.py", line 118, in __init__
    ('_relu', F.ReLU())
  File "/home/chainer-inception-score-master/inception_score.py", line 83, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)
Also for :
python example.py --model inception_score.model
  File "example.py", line 46, in <module>
    main(args)
  File "example.py", line 22, in main
    model = Inception()
  File "/home/chainer-inception-score-master/inception_score.py", line 118, in __init__
    ('_relu', F.ReLU())
  File "/home/chainer-inception-score-master/inception_score.py", line 83, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)
And could this code envaluate other GAN model?

**Comment by jononny** [comment]
my Environment is Ubuntu 14.04.5
Anaconda 2 with python  2.7.2 
tensorflow 1.3.0
all the packages are installed.

**Comment by hvy** [comment]
That `super()` syntax is for Python 3. You can either change [this line](https://github.com/hvy/chainer-inception-score/blob/master/inception_score.py#L83) to `super(Tower, self).__init__()` or you could use the future library or use Python 3.

I am not sure what you mean exactly with other GAN models but you can evaluate visual fidelity.

**Comment by jononny** [comment]
thank you reply, 
I mean that the how could I use this model, to give generated image a score about mean, and std, where I put my images to?

**Comment by hvy** [comment]
There are no assumptions about where to put the images nor how to read them, that's all up to you. If you mean the `example.py` script, since it relies on the Chainer dataset wrapper for CIFAR-10 you cannot without modifications reuse it for other images.

**Comment by hvy** [comment]
Let me close this ticket as it seems stale.
